= "let#(cr)#(lf)    // ══════════ 1. PARÂMETROS — ajuste aqui ══════════#(cr)#(lf)    Usuario         = ""Enrico"",#(cr)#(lf)    Pasta           = ""C:\Users\"" & Usuario & ""\Desktop\Power BI"",#(cr)#(lf)    // Se a Área de Trabalho estiver sincronizada no OneDrive, use uma destas:#(cr)#(lf)    //   ""C:\Users\"" & Usuario & ""\OneDrive\Desktop\Pasta nova""#(cr)#(lf)    //   ""C:\Users\"" & Usuario & ""\OneDrive\Área de Trabalho\Pasta nova""#(cr)#(lf)    // Para confirmar: Shift + botão direito na pasta → ""Copiar como caminho"".#(cr)#(lf)#(cr)#(lf)    LinhasParaPular = 0,     // linhas acima do cabeçalho (0 = cabeçalho na 1ª linha)#(cr)#(lf)    ColunasAlvo     = {#(cr)#(lf)        ""Campanha"", ""Salesforce"", ""Prioridade"", ""Sub Canal"",#(cr)#(lf)        ""Qtd Mailing Carregado"", ""APP"", ""Horario sugerido"",#(cr)#(lf)        ""QTDD ENVIAVEL"", ""STATUS"", ""Não Enviados"",#(cr)#(lf)        ""Hr Disparo"", ""Hr Finalizou"", ""FALHA""#(cr)#(lf)    },#(cr)#(lf)#(cr)#(lf)    // ══════════ 2. FUNÇÃO: extrai a data do nome do arquivo ══════════#(cr)#(lf)    // Procura o primeiro bloco isolado de 8 dígitos. Funciona com#(cr)#(lf)    // ""20260807.xlsx"", ""Disparos_20260807.xlsx"", ""Push - 20260807 v2.xlsx""#(cr)#(lf)    fxData = (nome as text) as nullable date =>#(cr)#(lf)        let#(cr)#(lf)            semExt    = Text.BeforeDelimiter(nome, ""."", {0, RelativePosition.FromEnd}),#(cr)#(lf)            tokens    = Text.SplitAny(semExt, "" _-()[].,""),#(cr)#(lf)            candidato = List.First(#(cr)#(lf)                            List.Select(tokens,#(cr)#(lf)                                each Text.Length(_) = 8 and Text.Select(_, {""0""..""9""}) = _),#(cr)#(lf)                            null)#(cr)#(lf)        in#(cr)#(lf)            if candidato = null then null#(cr)#(lf)            else try Date.FromText(#(cr)#(lf)                        Text.Start(candidato, 4) & ""-"" &#(cr)#(lf)                        Text.Middle(candidato, 4, 2) & ""-"" &#(cr)#(lf)                        Text.End(candidato, 2))#(cr)#(lf)                 otherwise null,#(cr)#(lf)#(cr)#(lf)    // ══════════ 3. LISTA OS ARQUIVOS ══════════#(cr)#(lf)    Fonte     = Folder.Files(Pasta),#(cr)#(lf)    SoExcel   = Table.SelectRows(Fonte,#(cr)#(lf)                    each ([Extension] = "".xlsx"" or [Extension] = "".xlsm"")#(cr)#(lf)                     and not Text.StartsWith([Name], ""~$"")),   // ignora temporários do Excel#(cr)#(lf)    ComData   = Table.AddColumn(SoExcel, ""DataDisparo"", each fxData([Name]), type date),#(cr)#(lf)    ValidData = Table.SelectRows(ComData, each [DataDisparo] <> null),#(cr)#(lf)#(cr)#(lf)    // ══════════ 4. ABRE CADA ARQUIVO ══════════#(cr)#(lf)    Livro    = Table.AddColumn(ValidData, ""Livro"", each Excel.Workbook([Content], true)),#(cr)#(lf)    Enxuto   = Table.SelectColumns(Livro, {""Name"", ""DataDisparo"", ""Livro""}),#(cr)#(lf)    ExpLivro = Table.ExpandTableColumn(Enxuto, ""Livro"",#(cr)#(lf)                    {""Name"", ""Data"", ""Kind""}, {""Aba"", ""Tabela"", ""Tipo""}),#(cr)#(lf)    SoAbas   = Table.SelectRows(ExpLivro, each [Tipo] = ""Sheet""),#(cr)#(lf)#(cr)#(lf)    // Se cada arquivo tiver mais de uma aba, filtre a certa:#(cr)#(lf)    // SoAbas = Table.SelectRows(SoAbas, each [Aba] = ""Disparos""),#(cr)#(lf)#(cr)#(lf)    // ══════════ 5. CABEÇALHO + NORMALIZAÇÃO DENTRO DE CADA ABA ══════════#(cr)#(lf)    // MissingField.UseNull impede que 1 arquivo com coluna faltando quebre tudo#(cr)#(lf)    Preparado = Table.TransformColumns(SoAbas, {""Tabela"", each#(cr)#(lf)                    Table.SelectColumns(#(cr)#(lf)                        Table.PromoteHeaders(Table.Skip(_, LinhasParaPular),#(cr)#(lf)                                             [PromoteAllScalars = true]),#(cr)#(lf)                        ColunasAlvo, MissingField.UseNull)}),#(cr)#(lf)#(cr)#(lf)    SoNecessario = Table.SelectColumns(Preparado, {""Name"", ""DataDisparo"", ""Aba"", ""Tabela""}),#(cr)#(lf)    Expandido    = Table.ExpandTableColumn(SoNecessario, ""Tabela"", ColunasAlvo),#(cr)#(lf)#(cr)#(lf)    // ══════════ 6. LIMPEZA ══════════#(cr)#(lf)    SemVazias = Table.SelectRows(Expandido,#(cr)#(lf)                    each [APP] <> null and Text.Trim(Text.From([APP] ?? """")) <> """"),#(cr)#(lf)#(cr)#(lf)    // Neutraliza #DIV/0!, #REF!, #N/D vindos das fórmulas manuais#(cr)#(lf)    SemErros = Table.ReplaceErrorValues(SemVazias, {#(cr)#(lf)                    {""QTDD ENVIAVEL"", null}, {""FALHA"", null},#(cr)#(lf)                    {""Qtd Mailing Carregado"", null}, {""Não Enviados"", null}}),#(cr)#(lf)#(cr)#(lf)    // ══════════ 7. TIPOS ══════════#(cr)#(lf)    // Se algum número vier como TEXTO no formato pt-BR (""30.579""), troque esta#(cr)#(lf)    // etapa por: Table.TransformColumnTypes(SemErros, {...}, ""pt-BR"")#(cr)#(lf)    Tipos = Table.TransformColumnTypes(SemErros, {#(cr)#(lf)                {""DataDisparo"",            type date},#(cr)#(lf)                {""Campanha"",               type text},#(cr)#(lf)                {""Salesforce"",             type text},#(cr)#(lf)                {""Prioridade"",             Int64.Type},#(cr)#(lf)                {""Sub Canal"",              type text},#(cr)#(lf)                {""Qtd Mailing Carregado"",  Int64.Type},#(cr)#(lf)                {""APP"",                    type text},#(cr)#(lf)                {""STATUS"",                 type text},#(cr)#(lf)                {""QTDD ENVIAVEL"",          Int64.Type},#(cr)#(lf)                {""Não Enviados"",           Int64.Type},#(cr)#(lf)                {""FALHA"",                  Int64.Type},#(cr)#(lf)                {""Horario sugerido"",       type time},#(cr)#(lf)                {""Hr Disparo"",             type time},#(cr)#(lf)                {""Hr Finalizou"",           type time}#(cr)#(lf)            }),#(cr)#(lf)#(cr)#(lf)    // ══════════ 8. TAXONOMIA: extrai Codigo, CPI e SO do nome Salesforce ══════════#(cr)#(lf)    // Padrão: <codigo>_<CPI>_<NOME>_<SO>#(cr)#(lf)    ComTokens = Table.AddColumn(Tipos, ""_tk"",#(cr)#(lf)                    each Text.Split(Text.From([Salesforce] ?? """"), ""_"")),#(cr)#(lf)#(cr)#(lf)    ComCodigo = Table.AddColumn(ComTokens, ""Codigo"", each#(cr)#(lf)                    if List.Count([_tk]) >= 1 then [_tk]{0} else null, type text),#(cr)#(lf)#(cr)#(lf)    // CPI = 2º token, e só se for todo numérico (evita pegar nome de campanha#(cr)#(lf)    // em linhas fora do padrão). Mantido como TEXTO para preservar os zeros à esquerda.#(cr)#(lf)    ComCPI = Table.AddColumn(ComCodigo, ""CPI"", each#(cr)#(lf)                    let t = [_tk] in#(cr)#(lf)                    if List.Count(t) >= 3 and t{1} <> """" and Text.Select(t{1}, {""0""..""9""}) = t{1}#(cr)#(lf)                    then t{1} else null, type text),#(cr)#(lf)#(cr)#(lf)    ComSOnome = Table.AddColumn(ComCPI, ""SO Nome"", each#(cr)#(lf)                    let u = Text.Upper(Text.From(List.Last([_tk], """"))) in#(cr)#(lf)                    if u = ""ANDROID"" then ""Android""#(cr)#(lf)                    else if u = ""IOS"" then ""iOS"" else null, type text),#(cr)#(lf)#(cr)#(lf)    ComSO = Table.AddColumn(ComSOnome, ""SO"", each#(cr)#(lf)                    let a = Text.Upper(Text.From([APP] ?? """")) in#(cr)#(lf)                    if   Text.Contains(a, ""ANDROID"") then ""Android""#(cr)#(lf)                    else if Text.Contains(a, ""IOS"")  then ""iOS""#(cr)#(lf)                    else ""Outro"", type text),#(cr)#(lf)#(cr)#(lf)    // Coluna de auditoria: SO no nome x SO na coluna APP#(cr)#(lf)    ComTaxonomia = Table.AddColumn(ComSO, ""Taxonomia"", each#(cr)#(lf)                    if      [CPI] = null              then ""CPI não identificado""#(cr)#(lf)                    else if [SO Nome] = null          then ""SO ausente no nome""#(cr)#(lf)                    else if [SO Nome] <> [SO]         then ""SO divergente do APP""#(cr)#(lf)                    else ""OK"", type text),#(cr)#(lf)#(cr)#(lf)    // Chave da ação. Se o CPI não sair do nome, cai para a Campanha —#(cr)#(lf)    // assim a desduplicação do mailing nunca deixa de funcionar.#(cr)#(lf)    ComChaveCPI = Table.AddColumn(ComTaxonomia, ""ChaveCPI"", each#(cr)#(lf)                    [CPI] ?? Text.From([Campanha] ?? ""SEM CHAVE""), type text),#(cr)#(lf)#(cr)#(lf)    ComChave = Table.AddColumn(ComChaveCPI, ""ChaveDisparo"", each#(cr)#(lf)                    Date.ToText([DataDisparo], [Format = ""yyyyMMdd""]) & ""|"" & [ChaveCPI],#(cr)#(lf)                    type text),#(cr)#(lf)#(cr)#(lf)    // ══════════ 9. COLUNAS DERIVADAS ══════════#(cr)#(lf)    ComAtraso = Table.AddColumn(ComChave, ""AtrasoMin"", each#(cr)#(lf)                    if [Hr Disparo] = null or [Horario sugerido] = null then null#(cr)#(lf)                    else Duration.TotalMinutes([Hr Disparo] - [Horario sugerido]), type number),#(cr)#(lf)#(cr)#(lf)    ComDuracao = Table.AddColumn(ComAtraso, ""DuracaoMin"", each#(cr)#(lf)                    if [Hr Disparo] = null or [Hr Finalizou] = null then null#(cr)#(lf)                    else Duration.TotalMinutes([Hr Finalizou] - [Hr Disparo]), type number),#(cr)#(lf)#(cr)#(lf)    ComQualidade = Table.AddColumn(ComDuracao, ""RegistroCompleto"", each#(cr)#(lf)                    if [QTDD ENVIAVEL] <> null and [FALHA] <> null and [Hr Finalizou] <> null#(cr)#(lf)                    then ""Completo"" else ""Incompleto"", type text),#(cr)#(lf)#(cr)#(lf)    Renomeado = Table.RenameColumns(ComQualidade, {{""Name"", ""ArquivoOrigem""}}),#(cr)#(lf)    Final     = Table.RemoveColumns(Renomeado, {""_tk""})#(cr)#(lf)in#(cr)#(lf)    Final"





